### ISSUE TITLE
Way to pause diffux_ci for debugging

### ISSUE THREAD

**Issue by lencioni** [diffux/diffux_ci#25]
I was trying to debug an example I was working on that wasn't rendering but had a difficult time because I couldn't figure out how to get things to pause so I could enter the browser's debugger. It would be nice if there was a documented way to do this.

**Comment by trotzig** [comment]
Until there's a documented way of doing this, you can use the undocumented:

1. Run `likadan review`. This will start a server at `localhost:4567`, and open a browser window for you pointing to `http://localhost:4567/review`.
2. Change the URL to just `http://localhost:4567`.
3. In the js console (in the browser), run `likadan.next(); likadan.renderCurrent();` a few times until you see your example.
