### ISSUE TITLE
Screenshots larger than viewport fail

### ISSUE THREAD

**Issue by kevinkehl** [diffux/diffux_ci#37]
If you are trying to create a screenshot larger than the configured viewport (e.g. a full page), ChunkyPNG fails with the error: 

`chunky_png-1.3.4/lib/chunky_png/canvas/operations.rb:175:in `crop!': Original image height is too small! (ChunkyPNG::OutOfBounds)`

**Comment by trotzig** [comment]
@kevinkehl can you provide a little more details, perhaps with an example? I know you looked into this and found some interesting bits.
