### ISSUE TITLE
Shorten command from diffux_ci to just diffux?

### ISSUE THREAD

**Issue by lencioni** [diffux/diffux_ci#43]
It is pretty unusual for a command to have an underscore in it, and I think that the `_ci` part might just be unnecessary. What do you think about shortening it? If not shortening, what about changing it to `diffux-ci` or `diffuxci`?

**Comment by lencioni** [comment]
@trotzig what do you think about this proposal?

**Comment by trotzig** [comment]
Sounds like a good idea! When I choose `diffux_ci`, I was under the impression that [diffux-core](https://github.com/diffux/diffux-core) already defined that command. But it turns out I was wrong.

**Comment by trotzig** [comment]
I'm currently working on this.
