### ISSUE TITLE
Duplicate bucket name

### ISSUE THREAD

**Issue by trotzig** [diffux/diffux_ci#60]
Bucket names are global for everyone. This is problematic since we've decided to use `diffux_ci-diffs` as the bucket name. When I try uploading diffs locally, I get

> /Users/henrictrotzig/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/s3-0.3.23/lib/s3/conne
ction.rb:216:in `handle_response': The requested bucket name is not available. The bucket
namespace is shared by all users of the system. Please select a different name and try aga
in. (S3::Error::BucketAlreadyExists)

We need to start using unique buckets per project. Perhaps the simplest solution is to add a `s3_bucket_name` configuration option?

**Comment by lencioni** [comment]
Ah, I didn't realize that bucket names were universal. I think adding a config option makes sense.
