### ISSUE TITLE
Try saving hashes of baseline images for speed improvement

### ISSUE THREAD

**Issue by lencioni** [diffux/diffux_ci#65]
I'm not sure if this would be a speed improvement or not, but if we save a hash of the baseline image next to the image, we can tell if the candidate image is identical by comparing the hashes. This _might_ be faster and use less memory because we won't have to read the whole baseline image off disk to do the comparison.

**Comment by trotzig** [comment]
This sounds like a good idea. It wouldn't cost much to test it out at least.

**Comment by trotzig** [comment]
We could save the hash in the filename, e.g. `snapshots/foo/baseline_321eaaa4c0dae6517e4ff1c828014c49.png` `snapshots/foo/candidate_511c35397ee57c1ba74e83256a850bf8.png`, then we wouldn't have to add another file with just the hashes.

**Comment by lencioni** [comment]
Looks like CityHash might be a good bet for speed. http://brainspec.com/blog/2012/10/29/fast-hashing-with-cityhash/

**Comment by lencioni** [comment]
Adding the hash in the filename might be okay, but I think it would be better to store it in a sidecar file, like `baseline.hash` or something because if we put it in the filename, we'll have to do a directory scan to figure out what it is.

**Comment by lencioni** [comment]
It turns out that installing cityhash on a mac is painful, so I'm going to try xxhash instead--which claims to be faster anyway.

**Comment by trotzig** [comment]
We could store the hash in a meta data field in the png.
http://www.w3.org/TR/PNG/#11textinfo

**Comment by lencioni** [comment]
I thought about stashing the hash in the meta data field but I wasn't sure if ChunkyPNG could read it without reading the whole file.

**Comment by lencioni** [comment]
I don't think we are going to see any speed improvements from this.

**Comment by trotzig** [comment]
Too bad, but thanks for trying!
