### ISSUE TITLE
Clean out snapshots from removed examples and sizes

### ISSUE THREAD

**Issue by lencioni** [diffux/diffux_ci#8]
When using diffux_ci in a project, we tend to change sizes on our diffux examples and remove old examples as we refactor our codebase. However, these all currently leave dangling snapshots. It would be nice to have a way to easily clean these out so the reviewer is always looking at new information.

**Comment by trotzig** [comment]
Good point. A quick-fix would be to add a "Delete" button next to each example in the Review view. We could also compile a list during a `likadan` run, and then provide an `rm -r` command in the output log. E.g. `rm -r snapshots/old_example_1 snapshots/old_example_2`.

**Comment by lencioni** [comment]
I noticed you recently added a command called `likadan prune`. Without knowing what it does, I would have expected the behavior outlined in this issue. Perhaps there is a better name for that command?

**Comment by trotzig** [comment]
You're probably right. I wasn't 100% on the `prune` name earlier and I can easily change it since no one is using it.

**Comment by trotzig** [comment]
I'm not sure this is even important anymore given that we don't really store snapshots in our CI setup. I'm closing this as a no-fix for now and then others can re-open if they think it's important.
