### ISSUE TITLE
Provide a way to include custom fonts

### ISSUE THREAD

**Issue by lencioni** [diffux/diffux_ci#82]
If a component's styles references a custom font using `@font-face` or whatnot, there should be a way for diffux to be configured to be able to serve up the required font files. I'm thinking something similar to the `stylesheets` configuration in the YAML file.

If there is a way to do this already, it should be documented.

cc @serena-w

**Comment by lencioni** [comment]
Perhaps we just need a way to specify a list of additional files that should be served by the diffux server.

**Comment by trotzig** [comment]
That sounds reasonable. We could perhaps also just fall back to the file system if a resource isn't found in server.rb.

**Comment by lencioni** [comment]
The trouble might be getting things from the correct paths. For instance, a file that needs to be served might be available in a subdirectory like `/public`, but it might be expected to be served from `/` or something else like that.

**Comment by trotzig** [comment]
Yeah, that's unfortunately (for us) a common pattern. In your case, what does the font-face declarations look like? And how are the files served?

**Comment by lencioni** [comment]
In this case, the `@font-face` declarations look like

```css
@font-face {
  font-family: "Circular";
  src: url("CircularAir-Book.otf");
  font-weight: normal;
  font-style: normal;
}
```

This happens to be in a CSS file in `public/`, which is right next to the font files. In this case, they expect to be served from the same location.

I wonder if we can come up with a solution that will be simple and general enough to work for stylesheets, fonts, and whatever else we might need.

**Comment by trotzig** [comment]
Would `public_folders` work? 

```yaml
public_folders: 
  - public
  - assets/export
```
when server.rb comes across something it doesn't know about, it will scan those folders to see if there's a file matching the path. E.g. `/foo/bar.otf` would be served by `public/foo/bar.otf` if `public` was in the `public_folders` configuration.

**Comment by lencioni** [comment]
Yeah that's about what I was thinking, but I wonder if it should be a map of directory to URL path?

```yaml
public_folders:
  public: /
  assets/export: /export
```

Also, we should perhaps call it `public_directories` instead.

**Comment by trotzig** [comment]
I guess that's a more general solution, although slightly more complicated than the straight up array. If we don't need the hash right away, we could roll with the array.
